name: Nightly Image Publish
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * */1
jobs:
  base:
    runs-on: ubuntu-latest
    if: github.actor == 'Sirherobrine23'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: checkout
        uses: actions/checkout@master

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            sirherobrine23/http-injector_server:latest
            sirherobrine23/http-injector_server:${{ github.run_id }}
            "linux/amd64","linux/arm64","linux/386","linux/arm/v7","linux/arm/v6"

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}