name: Nightly Image Publish
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * */1
jobs:
  base:
    runs-on: ubuntu-latest
    if: github.actor == 'Sirherobrine23'
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          username: sirherobrine23
          password: ${{ secrets.DOCKER_PASS }}
      - uses: actions/checkout@master

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            sirherobrine23/http-injector_server:nightly
          platforms: linux/amd64,linux/arm64,linux/386
