name: stable Image Publish
on:
  push:
    tags:
      - Stable**
      - V**
      - v**
jobs:
  base:
    runs-on: ubuntu-latest
    if: github.actor == 'Sirherobrine23'
    steps:
      - name: QEMMU Setup
        uses: docker/setup-qemu-action@v1
      - name: Buildx setup
        uses: docker/setup-buildx-action@v1
      - name: Docker login
        uses: docker/login-action@v1 
        with:
          username: sirherobrine23
          password: ${{ secrets.DOCKER_PASS }}
      - uses: actions/checkout@master
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            sirherobrine23/http-injector_server:latest
            sirherobrine23/http-injector_server:${{ github.run_id }}
          platforms: linux/amd64,linux/arm64
